import { DatabaseSync } from "node:sqlite";
import { randomUUID } from "node:crypto";
import type { CompanyDetail, CompanySourceSummary } from "../../src/shared/types.js";

const now=()=>new Date().toISOString();
export class Repository {
 private db:DatabaseSync;
 constructor(path:string,migration:string){ this.db=new DatabaseSync(path); this.db.exec("PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;"); this.db.exec(migration); this.db.exec("UPDATE collection_items SET status='PENDING', started_at=NULL, updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE status='RUNNING'"); }
 close(){this.db.close()}
 upsertTarget(searchKeyword:string,industryCode?:string,industryName?:string){const existing=this.db.prepare("SELECT target_id FROM collector_targets WHERE search_keyword=?").get(searchKeyword) as {target_id:string}|undefined;const id=existing?.target_id??randomUUID(),t=now();this.db.prepare(`INSERT INTO collector_targets(target_id,search_keyword,industry_code,industry_name,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(search_keyword) DO UPDATE SET industry_code=COALESCE(excluded.industry_code,collector_targets.industry_code),industry_name=COALESCE(excluded.industry_name,collector_targets.industry_name),updated_at=excluded.updated_at`).run(id,searchKeyword,industryCode??null,industryName??null,"READY",t,t);return id}
 attachJob(targetId:string,jobId:string){this.db.prepare("INSERT OR IGNORE INTO target_collection_jobs(target_id,collection_job_id,created_at) VALUES(?,?,?)").run(targetId,jobId,now())}
 checkpoint(targetId:string,page:number,row:number,kcd?:string,stats?:{completed:number;failed:number}){this.db.prepare("UPDATE collector_targets SET current_page=?,current_row_index=?,last_sminfo_kcd=COALESCE(?,last_sminfo_kcd),collected_count=COALESCE(?,collected_count),failed_count=COALESCE(?,failed_count),status='RUNNING',last_collected_at=?,updated_at=? WHERE target_id=?").run(page,row,kcd??null,stats?.completed??null,stats?.failed??null,now(),now(),targetId)}
 targetStatus(targetId:string,status:string,total?:number,pages?:number){this.db.prepare("UPDATE collector_targets SET status=?,total_results=COALESCE(?,total_results),total_pages=COALESCE(?,total_pages),updated_at=? WHERE target_id=?").run(status,total??null,pages??null,now(),targetId)}
 linkCollectedCompany(targetId:string,itemId:string,industryCode?:string){const row=this.db.prepare("SELECT company_id FROM collection_items WHERE collection_item_id=?").get(itemId) as {company_id:string}|undefined;if(!row?.company_id)return;const t=now();this.db.prepare("INSERT INTO company_industries(company_id,target_id,industry_code,created_at,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(company_id,target_id) DO UPDATE SET industry_code=COALESCE(excluded.industry_code,company_industries.industry_code),updated_at=excluded.updated_at").run(row.company_id,targetId,industryCode??null,t,t)}
 linkQueuedCompanies(targetId:string,jobId:string){const t=now();this.db.prepare("INSERT OR IGNORE INTO company_industries(company_id,target_id,created_at,updated_at) SELECT company_id,?,?,? FROM collection_items WHERE collection_job_id=? AND company_id IS NOT NULL").run(targetId,t,t,jobId)}
 createJob(total:number,pages:number,summary?:string,limit?:number){const id=randomUUID(),t=now();this.db.prepare("INSERT INTO collection_jobs(collection_job_id,status,search_summary,source_result_total,source_total_pages,dev_max_companies,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)").run(id,"READY",summary??null,total,pages,limit??null,t,t);return id}
 enqueue(jobId:string,page:number,rows:CompanySourceSummary[]){const stmt=this.db.prepare("INSERT OR IGNORE INTO collection_items(collection_item_id,collection_job_id,sminfo_kcd,company_name_snapshot,source_page_number,source_row_number,status,company_id,finished_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)");const existing=this.db.prepare("SELECT c.company_id,COALESCE(s.schema_version,0) schema_version FROM companies c LEFT JOIN company_detail_collection_state s ON s.company_id=c.company_id WHERE c.sminfo_kcd=?");this.db.exec("BEGIN IMMEDIATE");try{rows.forEach((x,i)=>{const found=existing.get(x.kcd) as {company_id:string;schema_version:number}|undefined;const complete=(found?.schema_version??0)>=4;const t=now();stmt.run(randomUUID(),jobId,x.kcd,x.companyName,page,i+1,complete?"SKIPPED":"PENDING",found?.company_id??null,complete?t:null,t,t)});this.db.exec("COMMIT")}catch(e){this.db.exec("ROLLBACK");throw e}}
 next(jobId:string){return this.db.prepare("SELECT collection_item_id,sminfo_kcd,company_name_snapshot FROM collection_items WHERE collection_job_id=? AND status='PENDING' ORDER BY source_page_number,source_row_number LIMIT 1").get(jobId) as {collection_item_id:string;sminfo_kcd:string;company_name_snapshot:string}|undefined}
 markRunning(id:string){this.db.prepare("UPDATE collection_items SET status='RUNNING',attempt_count=attempt_count+1,started_at=?,updated_at=? WHERE collection_item_id=?").run(now(),now(),id)}
 saveCompany(itemId:string,detail:CompanyDetail){const t=now(),companyId=(this.db.prepare("SELECT company_id FROM companies WHERE sminfo_kcd=?").get(detail.kcd) as {company_id:string}|undefined)?.company_id??randomUUID();this.db.exec("BEGIN IMMEDIATE");try{this.db.prepare(`INSERT INTO companies(company_id,sminfo_kcd,business_number,company_name,representative_name,company_type,company_status,established_date,address,road_address,homepage_url,main_products,ksic_code,industry_name,first_collected_at,last_collected_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(sminfo_kcd) DO UPDATE SET business_number=excluded.business_number,company_name=excluded.company_name,representative_name=excluded.representative_name,company_type=excluded.company_type,company_status=excluded.company_status,established_date=excluded.established_date,address=excluded.address,road_address=excluded.road_address,homepage_url=excluded.homepage_url,main_products=excluded.main_products,ksic_code=excluded.ksic_code,industry_name=excluded.industry_name,last_collected_at=excluded.last_collected_at,updated_at=excluded.updated_at`).run(companyId,detail.kcd,detail.businessNumber??null,detail.companyName,detail.representativeName??null,detail.companyType??null,detail.companyStatus??null,detail.establishedDate??null,detail.address??null,detail.roadAddress??null,detail.homepage??null,detail.mainProducts??null,detail.ksicCode??null,detail.industryName??null,t,t,t,t); const fs=this.db.prepare(`INSERT INTO company_financial_statements(financial_statement_id,company_id,fiscal_year,total_assets_krw_million,paid_in_capital_krw_million,total_equity_krw_million,revenue_krw_million,operating_income_krw_million,net_income_krw_million,collected_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(company_id,fiscal_year) DO UPDATE SET total_assets_krw_million=excluded.total_assets_krw_million,paid_in_capital_krw_million=excluded.paid_in_capital_krw_million,total_equity_krw_million=excluded.total_equity_krw_million,revenue_krw_million=excluded.revenue_krw_million,operating_income_krw_million=excluded.operating_income_krw_million,net_income_krw_million=excluded.net_income_krw_million,collected_at=excluded.collected_at,updated_at=excluded.updated_at`);for(const x of detail.financialStatements)fs.run(randomUUID(),companyId,x.fiscalYear,x.totalAssets??null,x.equity??null,x.totalCapital??null,x.revenue??null,x.operatingIncome??null,x.netIncome??null,t,t,t);
  this.db.prepare("DELETE FROM company_factories WHERE company_id=?").run(companyId);const factory=this.db.prepare("INSERT INTO company_factories(factory_id,company_id,factory_name,location_address,source_ordinal,collected_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)");(detail.factories??[]).forEach((x,i)=>factory.run(randomUUID(),companyId,x.factoryName??null,x.locationAddress??null,i,t,t,t));
  this.db.prepare("DELETE FROM company_patents WHERE company_id=?").run(companyId);const patent=this.db.prepare("INSERT INTO company_patents(patent_id,company_id,patent_date,description,source_ordinal,collected_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)");(detail.patents??[]).forEach((x,i)=>patent.run(randomUUID(),companyId,x.patentDate??null,x.description??null,i,t,t,t));
  this.db.prepare("DELETE FROM company_executives WHERE company_id=?").run(companyId);const executive=this.db.prepare("INSERT INTO company_executives(executive_id,company_id,position_title,masked_name,source_ordinal,collected_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)");(detail.executives??[]).forEach((x,i)=>executive.run(randomUUID(),companyId,x.positionTitle??null,x.maskedName??null,i,t,t,t));
  this.db.prepare("DELETE FROM company_business_sites WHERE company_id=?").run(companyId);const site=this.db.prepare("INSERT INTO company_business_sites(business_site_id,company_id,site_name,site_type,business_number,address,source_ordinal,collected_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)");(detail.businessSites??[]).forEach((x,i)=>site.run(randomUUID(),companyId,x.siteName??null,x.siteType??null,x.businessNumber??null,x.address??null,i,t,t,t));
  this.db.prepare("DELETE FROM company_histories WHERE company_id=?").run(companyId);const history=this.db.prepare("INSERT INTO company_histories(history_id,company_id,event_date,description,source_ordinal,collected_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)");(detail.histories??[]).forEach((x,i)=>history.run(randomUUID(),companyId,x.eventDate??null,x.description??null,i,t,t,t));
  this.db.prepare("DELETE FROM company_certifications WHERE company_id=?").run(companyId);const certification=this.db.prepare("INSERT INTO company_certifications(certification_id,company_id,certification_name,certification_number,issuer,acquired_date,valid_until,source_ordinal,collected_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)");(detail.certifications??[]).forEach((x,i)=>certification.run(randomUUID(),companyId,x.certificationName??null,x.certificationNumber??null,x.issuer??null,x.acquiredDate??null,x.validUntil??null,i,t,t,t));
  this.db.prepare("DELETE FROM company_designations WHERE company_id=?").run(companyId);const designation=this.db.prepare("INSERT INTO company_designations(designation_id,company_id,designation_name,designation_number,authority,designated_date,valid_until,source_ordinal,collected_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)");(detail.designations??[]).forEach((x,i)=>designation.run(randomUUID(),companyId,x.designationName??null,x.designationNumber??null,x.authority??null,x.designatedDate??null,x.validUntil??null,i,t,t,t));
  this.db.prepare("INSERT INTO company_detail_collection_state(company_id,schema_version,collected_at,updated_at) VALUES(?,?,?,?) ON CONFLICT(company_id) DO UPDATE SET schema_version=excluded.schema_version,collected_at=excluded.collected_at,updated_at=excluded.updated_at").run(companyId,4,t,t);
  this.db.prepare("UPDATE collection_items SET status='DONE',company_id=?,finished_at=?,error_code=NULL,error_message=NULL,updated_at=? WHERE collection_item_id=?").run(companyId,t,t,itemId);this.db.exec("COMMIT");}catch(e){this.db.exec("ROLLBACK");throw e}}
 fail(itemId:string,code:string,message:string){this.db.prepare("UPDATE collection_items SET status='FAILED',error_code=?,error_message=?,finished_at=?,updated_at=? WHERE collection_item_id=?").run(code,message.slice(0,500),now(),now(),itemId)}
 stats(jobId:string){return this.db.prepare("SELECT COUNT(*) total,SUM(status='DONE') completed,SUM(status='FAILED') failed,SUM(status='PENDING') pending FROM collection_items WHERE collection_job_id=?").get(jobId) as {total:number;completed:number;failed:number;pending:number}}
 jobStatus(id:string,status:string){this.db.prepare("UPDATE collection_jobs SET status=?,started_at=COALESCE(started_at,?),completed_at=CASE WHEN ?='COMPLETED' THEN ? ELSE completed_at END,updated_at=? WHERE collection_job_id=?").run(status,now(),status,now(),now(),id)}
}
