import { DatabaseSync } from "node:sqlite";
import { randomUUID } from "node:crypto";
import type { CompanyDetail, CompanySourceSummary, DetailSectionName, SectionStatus } from "../../src/shared/types.js";

const now=()=>new Date().toISOString();
export const COLLECTOR_SCHEMA_VERSION=6;
export const DETAIL_REVERIFY_AFTER_MS=30*24*60*60*1000;
const replaceable=(status:SectionStatus)=>status==="VERIFIED"||status==="CONFIRMED_EMPTY";

export class Repository {
 private db:DatabaseSync;
 constructor(path:string,migration:string){
  this.db=new DatabaseSync(path);
  this.db.exec("PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;");
  this.db.exec(migration);
  this.db.exec("UPDATE collection_items SET status='PENDING',started_at=NULL,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE status='RUNNING'");
 }
 close(){this.db.close()}
 raw(){return this.db}
 event(jobId:string,itemId:string|undefined,eventType:string,message:string,severity="INFO"){
  const t=now();this.db.prepare("INSERT INTO collection_events(collection_event_id,collection_job_id,collection_item_id,event_type,severity,message,occurred_at,created_at) VALUES(?,?,?,?,?,?,?,?)").run(randomUUID(),jobId,itemId??null,eventType,severity,message.slice(0,1000),t,t);
 }
 upsertTarget(searchKeyword:string,industryCode?:string,industryName?:string){const existing=this.db.prepare("SELECT target_id FROM collector_targets WHERE search_keyword=?").get(searchKeyword) as {target_id:string}|undefined;const id=existing?.target_id??randomUUID(),t=now();this.db.prepare(`INSERT INTO collector_targets(target_id,search_keyword,industry_code,industry_name,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(search_keyword) DO UPDATE SET industry_code=COALESCE(excluded.industry_code,collector_targets.industry_code),industry_name=COALESCE(excluded.industry_name,collector_targets.industry_name),updated_at=excluded.updated_at`).run(id,searchKeyword,industryCode??null,industryName??null,"READY",t,t);return id}
 attachJob(targetId:string,jobId:string){this.db.prepare("INSERT OR IGNORE INTO target_collection_jobs(target_id,collection_job_id,created_at) VALUES(?,?,?)").run(targetId,jobId,now())}
 checkpoint(targetId:string,page:number,row:number,kcd?:string,stats?:{completed:number;failed:number}){this.db.prepare("UPDATE collector_targets SET current_page=?,current_row_index=?,last_sminfo_kcd=COALESCE(?,last_sminfo_kcd),collected_count=COALESCE(?,collected_count),failed_count=COALESCE(?,failed_count),status='RUNNING',last_collected_at=?,updated_at=? WHERE target_id=?").run(page,row,kcd??null,stats?.completed??null,stats?.failed??null,now(),now(),targetId)}
 targetStatus(targetId:string,status:string,total?:number,pages?:number){this.db.prepare("UPDATE collector_targets SET status=?,total_results=COALESCE(?,total_results),total_pages=COALESCE(?,total_pages),updated_at=? WHERE target_id=?").run(status,total??null,pages??null,now(),targetId)}
 linkCollectedCompany(targetId:string,itemId:string,industryCode?:string){const row=this.db.prepare("SELECT company_id FROM collection_items WHERE collection_item_id=?").get(itemId) as {company_id:string}|undefined;if(!row?.company_id)return;const t=now();this.db.prepare("INSERT INTO company_industries(company_id,target_id,industry_code,created_at,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(company_id,target_id) DO UPDATE SET industry_code=COALESCE(excluded.industry_code,company_industries.industry_code),updated_at=excluded.updated_at").run(row.company_id,targetId,industryCode??null,t,t)}
 linkQueuedCompanies(targetId:string,jobId:string){const t=now();this.db.prepare("INSERT OR IGNORE INTO company_industries(company_id,target_id,created_at,updated_at) SELECT company_id,?,?,? FROM collection_items WHERE collection_job_id=? AND company_id IS NOT NULL").run(targetId,t,t,jobId)}
 createJob(total:number,pages:number,summary?:string,limit?:number){const id=randomUUID(),t=now();this.db.prepare("INSERT INTO collection_jobs(collection_job_id,status,search_summary,source_result_total,source_total_pages,dev_max_companies,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)").run(id,"READY",summary??null,total,pages,limit??null,t,t);this.event(id,undefined,"COLLECTION_STARTED",`Job created: source_total=${total}, pages=${pages}`);return id}

 enqueue(jobId:string,page:number,rows:CompanySourceSummary[]){
  const item=this.db.prepare("INSERT OR IGNORE INTO collection_items(collection_item_id,collection_job_id,sminfo_kcd,company_name_snapshot,source_page_number,source_row_number,status,company_id,finished_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)");
  const find=this.db.prepare("SELECT c.company_id,s.collection_quality,s.last_detail_verified_at FROM companies c LEFT JOIN company_collection_state s ON s.company_id=c.company_id WHERE c.sminfo_kcd=?");
  this.db.exec("BEGIN IMMEDIATE");
  try{for(const [i,x] of rows.entries()){
   const t=now();let found=find.get(x.kcd) as {company_id:string;collection_quality?:string;last_detail_verified_at?:string}|undefined;
   if(!found){
    const companyId=randomUUID();
    this.db.prepare("INSERT INTO companies(company_id,sminfo_kcd,company_name,representative_name,company_type,road_address,industry_name,first_collected_at,last_collected_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run(companyId,x.kcd,x.companyName,x.representativeName??null,x.companyType??null,x.roadAddress??null,x.industryName??null,t,t,t,t);
    this.db.prepare("INSERT INTO company_collection_state(company_id,collection_quality,collector_schema_version,first_seen_at,last_seen_at,created_at,updated_at) VALUES(?,'UNKNOWN',?,?,?,?,?)").run(companyId,COLLECTOR_SCHEMA_VERSION,t,t,t,t);
    found={company_id:companyId,collection_quality:"UNKNOWN"};
    this.event(jobId,undefined,"COMPANY_DISCOVERED",`Discovered ${x.kcd} ${x.companyName}`);
   }else{
    this.db.prepare("INSERT OR IGNORE INTO company_collection_state(company_id,collection_quality,collector_schema_version,first_seen_at,last_seen_at,created_at,updated_at) VALUES(?,'UNKNOWN',?,?,?,?,?)").run(found.company_id,COLLECTOR_SCHEMA_VERSION,t,t,t,t);
    this.db.prepare("UPDATE company_collection_state SET last_seen_at=?,updated_at=? WHERE company_id=?").run(t,t,found.company_id);
   }
   const fresh=found.collection_quality==="VERIFIED"&&Boolean(found.last_detail_verified_at)&&Date.parse(found.last_detail_verified_at!)>=Date.now()-DETAIL_REVERIFY_AFTER_MS;
   const status=fresh?"SKIPPED":"PENDING";const itemId=randomUUID();
   item.run(itemId,jobId,x.kcd,x.companyName,page,i+1,status,found.company_id,fresh?t:null,t,t);
   if(fresh)this.event(jobId,itemId,"COMPANY_SKIPPED",`Fresh VERIFIED detail skipped: ${x.kcd}`);
  }this.db.exec("COMMIT");}catch(e){this.db.exec("ROLLBACK");throw e}
 }
 next(jobId:string){return this.db.prepare("SELECT collection_item_id,sminfo_kcd,company_name_snapshot,source_page_number,source_row_number FROM collection_items WHERE collection_job_id=? AND status='PENDING' ORDER BY source_page_number,source_row_number LIMIT 1").get(jobId) as {collection_item_id:string;sminfo_kcd:string;company_name_snapshot:string;source_page_number:number;source_row_number:number}|undefined}
 markRunning(id:string){this.db.prepare("UPDATE collection_items SET status='RUNNING',attempt_count=attempt_count+1,started_at=?,updated_at=? WHERE collection_item_id=?").run(now(),now(),id)}

 saveCompany(itemId:string,detail:CompanyDetail){
  const legacyCounts:Record<DetailSectionName,number>={basic_info:detail.companyName?1:0,financial:detail.financialStatements.length,executive:detail.executives?.length??0,business_site:detail.businessSites?.length??0,history:detail.histories?.length??0,certification:detail.certifications?.length??0,designation:detail.designations?.length??0};
  const fallbackStatuses=Object.fromEntries((Object.keys(legacyCounts) as DetailSectionName[]).map(name=>[name,{status:(legacyCounts[name]>0?"VERIFIED":"CONFIRMED_EMPTY") as SectionStatus,error:"LEGACY_CALL_WITHOUT_SECTION_STATUS"}]));
  const sectionStatuses=detail.sectionStatuses??fallbackStatuses as CompanyDetail["sectionStatuses"];
  const collectionQuality=detail.collectionQuality??"UNKNOWN";
  const t=now();const item=this.db.prepare("SELECT collection_job_id FROM collection_items WHERE collection_item_id=?").get(itemId) as {collection_job_id:string};
  const existing=this.db.prepare("SELECT company_id FROM companies WHERE sminfo_kcd=?").get(detail.kcd) as {company_id:string}|undefined;
  const companyId=existing?.company_id??randomUUID();
  if(detail.businessNumber){const conflict=this.db.prepare("SELECT company_id,sminfo_kcd FROM companies WHERE business_number=? AND company_id<>?").get(detail.businessNumber,companyId) as {company_id:string;sminfo_kcd:string}|undefined;if(conflict)throw new Error(`IDENTITY_CONFLICT business_number=${detail.businessNumber} existing_kcd=${conflict.sminfo_kcd} incoming_kcd=${detail.kcd}`)}
  this.db.exec("BEGIN IMMEDIATE");
  try{
   this.db.prepare(`INSERT INTO companies(company_id,sminfo_kcd,business_number,company_name,representative_name,company_type,company_status,established_date,address,road_address,homepage_url,main_products,ksic_code,industry_name,first_collected_at,last_collected_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(sminfo_kcd) DO UPDATE SET business_number=COALESCE(excluded.business_number,companies.business_number),company_name=CASE WHEN excluded.company_name<>'' THEN excluded.company_name ELSE companies.company_name END,representative_name=COALESCE(excluded.representative_name,companies.representative_name),company_type=COALESCE(excluded.company_type,companies.company_type),company_status=COALESCE(excluded.company_status,companies.company_status),established_date=COALESCE(excluded.established_date,companies.established_date),address=COALESCE(excluded.address,companies.address),road_address=COALESCE(excluded.road_address,companies.road_address),homepage_url=COALESCE(excluded.homepage_url,companies.homepage_url),main_products=COALESCE(excluded.main_products,companies.main_products),ksic_code=COALESCE(excluded.ksic_code,companies.ksic_code),industry_name=COALESCE(excluded.industry_name,companies.industry_name),last_collected_at=excluded.last_collected_at,updated_at=excluded.updated_at`).run(companyId,detail.kcd,detail.businessNumber??null,detail.companyName,detail.representativeName??null,detail.companyType??null,detail.companyStatus??null,detail.establishedDate??null,detail.address??null,detail.roadAddress??null,detail.homepage??null,detail.mainProducts??null,detail.ksicCode??null,detail.industryName??null,t,t,t,t);
   if(detail.sourceUpdatedAt)this.db.prepare("UPDATE companies SET source_updated_at=? WHERE sminfo_kcd=?").run(detail.sourceUpdatedAt,detail.kcd);
   if(replaceable(sectionStatuses.financial.status)&&sectionStatuses.financial.status==="VERIFIED"){
    const fs=this.db.prepare(`INSERT INTO company_financial_statements(financial_statement_id,company_id,fiscal_year,total_assets_krw_million,paid_in_capital_krw_million,total_equity_krw_million,revenue_krw_million,operating_income_krw_million,net_income_krw_million,collected_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(company_id,fiscal_year) DO UPDATE SET total_assets_krw_million=COALESCE(excluded.total_assets_krw_million,company_financial_statements.total_assets_krw_million),paid_in_capital_krw_million=COALESCE(excluded.paid_in_capital_krw_million,company_financial_statements.paid_in_capital_krw_million),total_equity_krw_million=COALESCE(excluded.total_equity_krw_million,company_financial_statements.total_equity_krw_million),revenue_krw_million=COALESCE(excluded.revenue_krw_million,company_financial_statements.revenue_krw_million),operating_income_krw_million=COALESCE(excluded.operating_income_krw_million,company_financial_statements.operating_income_krw_million),net_income_krw_million=COALESCE(excluded.net_income_krw_million,company_financial_statements.net_income_krw_million),collected_at=excluded.collected_at,updated_at=excluded.updated_at`);
    for(const x of detail.financialStatements)fs.run(randomUUID(),companyId,x.fiscalYear,x.totalAssets??null,x.equity??null,x.totalCapital??null,x.revenue??null,x.operatingIncome??null,x.netIncome??null,t,t,t);
   }
   const replace=(section:DetailSectionName,table:string,idColumn:string,sql:string,rows:any[],values:(x:any,i:number)=>any[])=>{const status=sectionStatuses[section].status;if(!replaceable(status))return;this.db.prepare(`DELETE FROM ${table} WHERE company_id=?`).run(companyId);if(status==="CONFIRMED_EMPTY")return;const stmt=this.db.prepare(sql);rows.forEach((x,i)=>stmt.run(randomUUID(),companyId,...values(x,i),t,t,t));};
   replace("executive","company_source_executives","executive_id","INSERT INTO company_source_executives(executive_id,company_id,source_number,position_title,masked_name,source_ordinal,collected_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)",detail.executives??[],(x,i)=>[x.sourceNumber??null,x.positionTitle??null,x.maskedName??null,i]);
   replace("business_site","company_source_business_sites","business_site_id","INSERT INTO company_source_business_sites(business_site_id,company_id,site_name,site_address,source_ordinal,collected_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)",detail.businessSites??[],(x,i)=>[x.siteName??null,x.siteAddress??null,i]);
   replace("history","company_source_histories","history_id","INSERT INTO company_source_histories(history_id,company_id,source_number,event_date,description,source_ordinal,collected_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)",detail.histories??[],(x,i)=>[x.sourceNumber??null,x.eventDate??null,x.description??null,i]);
   replace("certification","company_source_certifications","certification_id","INSERT INTO company_source_certifications(certification_id,company_id,certification_number,certification_name,certification_scope,validity_period,certification_authority,source_ordinal,collected_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)",detail.certifications??[],(x,i)=>[x.certificationNumber??null,x.certificationName??null,x.certificationScope??null,x.validityPeriod??null,x.certificationAuthority??null,i]);
   replace("designation","company_source_designations","designation_id","INSERT INTO company_source_designations(designation_id,company_id,designation_number,designation_name,validity_period,operating_authority,source_ordinal,collected_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)",detail.designations??[],(x,i)=>[x.designationNumber??null,x.designationName??null,x.validityPeriod??null,x.operatingAuthority??null,i]);
   const sectionState=this.db.prepare(`INSERT INTO company_section_collection_state(company_id,section_name,status,verified_at,last_attempted_at,error_message,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(company_id,section_name) DO UPDATE SET status=excluded.status,verified_at=CASE WHEN excluded.status IN ('VERIFIED','CONFIRMED_EMPTY') THEN excluded.verified_at ELSE company_section_collection_state.verified_at END,last_attempted_at=excluded.last_attempted_at,error_message=excluded.error_message,updated_at=excluded.updated_at`);
   for(const [name,result] of Object.entries(sectionStatuses))sectionState.run(companyId,name,result.status,replaceable(result.status)?t:null,t,result.error??null,t);
   this.db.prepare(`INSERT INTO company_collection_state(company_id,collection_quality,collector_schema_version,first_seen_at,last_seen_at,last_collected_at,last_detail_verified_at,last_error_code,last_error_message,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(company_id) DO UPDATE SET collection_quality=excluded.collection_quality,collector_schema_version=excluded.collector_schema_version,last_seen_at=COALESCE(company_collection_state.last_seen_at,excluded.last_seen_at),last_collected_at=excluded.last_collected_at,last_detail_verified_at=CASE WHEN excluded.collection_quality='VERIFIED' THEN excluded.last_detail_verified_at ELSE company_collection_state.last_detail_verified_at END,last_error_code=NULL,last_error_message=NULL,updated_at=excluded.updated_at`).run(companyId,collectionQuality,COLLECTOR_SCHEMA_VERSION,t,t,t,collectionQuality==="VERIFIED"?t:null,null,null,t,t);
   this.db.prepare("INSERT INTO company_detail_collection_state(company_id,schema_version,collected_at,updated_at) VALUES(?,?,?,?) ON CONFLICT(company_id) DO UPDATE SET schema_version=excluded.schema_version,collected_at=excluded.collected_at,updated_at=excluded.updated_at").run(companyId,COLLECTOR_SCHEMA_VERSION,t,t);
   this.db.prepare("UPDATE collection_items SET status='DONE',company_id=?,finished_at=?,error_code=NULL,error_message=NULL,updated_at=? WHERE collection_item_id=?").run(companyId,t,t,itemId);
   this.event(item.collection_job_id,itemId,collectionQuality==="VERIFIED"?"DETAIL_VERIFIED":"DETAIL_PARTIAL",`${detail.kcd}: ${collectionQuality}`);
   this.db.exec("COMMIT");
 }catch(e){this.db.exec("ROLLBACK");throw e}
 }
 fail(itemId:string,code:string,message:string){const t=now();const row=this.db.prepare("SELECT collection_job_id,company_id FROM collection_items WHERE collection_item_id=?").get(itemId) as {collection_job_id:string;company_id?:string};this.db.prepare("UPDATE collection_items SET status='FAILED',error_code=?,error_message=?,finished_at=?,updated_at=? WHERE collection_item_id=?").run(code,message.slice(0,500),t,t,itemId);if(row?.company_id){this.db.prepare("UPDATE company_collection_state SET collection_quality=CASE WHEN collection_quality='VERIFIED' THEN collection_quality ELSE 'FAILED' END,last_error_code=?,last_error_message=?,last_collected_at=?,updated_at=? WHERE company_id=?").run(code,message.slice(0,500),t,t,row.company_id);const section=this.db.prepare(`INSERT INTO company_section_collection_state(company_id,section_name,status,last_attempted_at,error_message,updated_at) VALUES(?,?,'FAILED',?,?,?) ON CONFLICT(company_id,section_name) DO UPDATE SET status=CASE WHEN company_section_collection_state.status IN ('VERIFIED','CONFIRMED_EMPTY') THEN company_section_collection_state.status ELSE 'FAILED' END,last_attempted_at=excluded.last_attempted_at,error_message=excluded.error_message,updated_at=excluded.updated_at`);for(const name of ["basic_info","financial","executive","business_site","history","certification","designation"])section.run(row.company_id,name,t,message.slice(0,500),t)}this.event(row.collection_job_id,itemId,code==="ACCESS_RESTRICTED"?"ACCESS_RESTRICTED":"DETAIL_FAILED",message,"ERROR")}
 skip(itemId:string,code:string,message:string){const t=now();const row=this.db.prepare("SELECT collection_job_id FROM collection_items WHERE collection_item_id=?").get(itemId) as {collection_job_id:string};this.db.prepare("UPDATE collection_items SET status='SKIPPED',error_code=?,error_message=?,finished_at=?,updated_at=? WHERE collection_item_id=?").run(code,message.slice(0,500),t,t,itemId);this.event(row.collection_job_id,itemId,code,message,"INFO")}
 stats(jobId:string){const row=this.db.prepare("SELECT COUNT(*) total,COALESCE(SUM(status='DONE'),0) completed,COALESCE(SUM(status='FAILED'),0) failed,COALESCE(SUM(status='PENDING'),0) pending,COALESCE(SUM(status='SKIPPED'),0) skipped FROM collection_items WHERE collection_job_id=?").get(jobId) as {total:number;completed:number;failed:number;pending:number;skipped:number};return row}
 jobStatus(id:string,status:string){const stats=this.stats(id),terminal=status==="COMPLETED"||status==="ERROR"||status==="STOPPED";this.db.prepare("UPDATE collection_jobs SET status=?,completed_count=?,failed_count=?,skipped_count=?,started_at=COALESCE(started_at,?),completed_at=CASE WHEN ? THEN ? ELSE completed_at END,updated_at=? WHERE collection_job_id=?").run(status,stats.completed,stats.failed,stats.skipped,now(),terminal?1:0,now(),now(),id);if(status==="PAUSED")this.event(id,undefined,"COLLECTION_PAUSED",`completed=${stats.completed}, failed=${stats.failed}`);if(terminal)this.event(id,undefined,"COLLECTION_COMPLETED",`status=${status}, completed=${stats.completed}, failed=${stats.failed}, skipped=${stats.skipped}`,status==="ERROR"?"ERROR":"INFO")}
 finishJob(id:string){const stats=this.stats(id);const status=stats.failed>0?"ERROR":"COMPLETED";this.jobStatus(id,status);return {status,...stats}}
}
